import express from 'express';
import cors from 'cors';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { config } from './config.js';
import authRoutes from './routes/auth-routes.js';
import senderRoutes from './routes/sender-routes.js';
import processRoutes from './routes/process-routes.js';
import referenceRoutes from './routes/reference-routes.js';
import adminRoutes from './routes/admin-routes.js';
import auditRoutes from './routes/audit-routes.js';
import reportRoutes from './routes/report-routes.js';
import { errorHandler, notFound } from './middlewares/errors.js';

fs.mkdirSync(config.uploadDir, { recursive: true });
const currentDirectory = path.dirname(fileURLToPath(import.meta.url));
const clientDirectory = path.resolve(currentDirectory, '../../client');
const app = express();
app.use(cors({ origin: config.clientOrigin }));
app.use(express.json({ limit: '1mb' }));
app.get('/api/health', (request, response) => response.json({ status: 'ok' }));
app.use('/api/auth', authRoutes);
app.use('/api/senders', senderRoutes);
app.use('/api/processes', processRoutes);
app.use('/api', referenceRoutes);
app.use('/api/admin', adminRoutes);
app.use('/api/audit-logs', auditRoutes);
app.use('/api/reports', reportRoutes);
app.use(express.static(clientDirectory));
app.use(notFound);
app.use(errorHandler);
app.listen(config.port, () => console.log(`SGEPA API disponível em http://localhost:${config.port}`));
